version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./node/Dockerfile
    image: react-jblog-admin_image
    container_name: 'react-jblog-admin_container'
    environment:
    - NODE_ENV=production
    ports:
    - 8091:8091
    restart: always



